Resources:
  TrainingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableTraining}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: trainingId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: trainingId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  SeasonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableSeason}
      AttributeDefinitions:
        - AttributeName: seasonId
          AttributeType: S
      KeySchema:
        - AttributeName: seasonId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
